name: Terraform Version Check

on:
  workflow_dispatch:  # allows manual triggering from GitHub UI

jobs:
  check-terraform-version:
    runs-on: mini

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📌 Show Terraform version
        run: terraform version
