name: Terraform Destroy for Test and Staging Environments

on:
  workflow_dispatch:  # Manual trigger

jobs:
  terraform-destroy:
    name: Destroy Test and Staging
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init (Test)
        run: terraform init -backend-config=env/test/backend.tfvars

      - name: Terraform Destroy (Test)
        run: terraform destroy -var-file=test.tfvars -auto-approve

    