name: Terraform CI for Test Environment

on:
  workflow_dispatch:  

jobs:
  plan:
    name: Terraform Plan
    runs-on: self-hosted

    environment:
      name: test
  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -backend-config=env/test/backend.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file=env/test/test.tfvars

      
    apply:
    name: Terraform apply
    runs-on: self-hosted
    needs: plan


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -backend-config=env/test/backend.tfvars


      - name: Terraform Apply
        run: terraform apply -var-file=env/test/test.tfvars -auto-approve
