name: Terraform CI for Test Environment

on:
  workflow_dispatch:  

jobs:
  terraform:
    name: Terraform Init, Plan and Apply
    runs-on: self-hosted

    environment:
      name: test
  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Terraform Init
        working-directory: ./env
        run: terraform init

      - name: Terraform Plan
        working-directory: ./env
        run: terraform plan -var-file=test/test.tfvars

      - name: Terraform Apply
        working-directory: ./env
        run: terraform apply -var-file=test/test.tfvars -auto-approve
